In [1]:
import numpy as np

In [3]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((5,5))  #Metrix of 1 with 5 col and 5 row

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
np.empty((3,3)) 

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.49798477e-321],
       [6.95271921e-310, 8.78548181e-279, 1.13135215e-311]])

In [67]:
myList = [1,4,5,7]       #List
np.array(myList)         #Convert list into array

array([1, 4, 5, 7])

In [72]:
x = np.arange(1,100,10)     #Get Shape
x.shape

(10,)

In [74]:
x = np.zeros((10,10))       #Get Shape
x.shape

(10, 10)

In [79]:
y = x.reshape((2,2,5,5))        #Reshape
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [80]:
y.dtype         #Check Type

dtype('float64')

In [83]:
y.ndim          #Check Dimension

4